# Generated by Django 2.0.5 on 2018-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('my_type', models.IntegerField(blank=True, null=True)),
                ('public', models.NullBooleanField()),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=840, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('social_created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(blank=True, null=True)),
                ('askroom_id', models.ForeignKey(blank=True, db_column='askroom_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Askrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_submitted', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=840, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=840, null=True)),
                ('askroom_id', models.ForeignKey(blank=True, db_column='askroom_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Askrooms')),
                ('current_version', models.ForeignKey(blank=True, db_column='current_version', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Questions')),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('question_id', models.ForeignKey(blank=True, db_column='question_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Questions')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=126)),
                ('full_account', models.NullBooleanField()),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='privileges',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Users'),
        ),
    ]
