# Generated by Django 2.0.5 on 2018-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='email',
        ),
        migrations.AddField(
            model_name='privilege',
            name='access_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
