# Generated by Django 2.0.5 on 2018-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='askrooms',
            name='social_created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='content',
            field=models.CharField(blank=True, max_length=840, null=True),
        ),
    ]
