# Generated by Django 2.0.5 on 2018-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20180525_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='display_name',
        ),
    ]
